### ISSUE TITLE
Rotate API Key every 6 month

### ISSUE THREAD

**Issue by air5451** [air5451/ForgetMeNot#11]
Right now petfinder API key need to be provided in config and will expire after 6 month. There mast be a better way to handle it.
May be get it from a central storage (keyvault)
Will users need to authenticate? How to maintain a repository of authorized users?

**Comment by leviherpel** [comment]
The actual key rotation seems to still have to be manual as you have to manually log into PetFinder to renew another one. I don't think PetFinder has automated that action. If it is automatable, could be done with an azure function.
